{{- if not .Values.externalMongoDB.enabled -}}
{{- $pass := randAlphaNum 32 }}
{{- $username := randAlphaNum 5 }}

apiVersion: v1
data:
  MONGODB_PASSWORD: {{ $pass | b64enc}}
  MONGODB_DATABASE: {{ "statuses" | b64enc}}
  MONGODB_USERNAME: {{ $username | b64enc}}
  MONGODB_ROOT_PASSWORD: {{ randAlphaNum 32 | b64enc}}
  MONGO_DB_DSN: {{ printf "mongodb://%s:%s@%s-mongodb-service:27017/statuses" $username $pass (include "status-service.fullname" .) | b64enc }}
kind: Secret
metadata:
  name: {{ include "status-service.fullname" . }}-mongodb-credentials
  labels:
    {{- include "status-service.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
{{- end -}}
