{{- if .Values.createRBAC -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "status-service.fullname" . }}-crd
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["appmirage.io"]
    resources: ["statusservices", "statusservicesgroup"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

{{- end -}}
