{{- if not .Values.externalMongoDB.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "status-service.fullname" . }}-mongodb
spec:
  serviceName: "{{ include "status-service.fullname" . }}-mongodb-service"
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.statefulset-{{ .Release.Namespace }}-mongodb-master
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "status-service.fullname" . }}-mongodb
        role: master
        workload.user.cattle.io/workloadselector: apps.statefulset-{{ .Release.Namespace }}-mongodb-master
    spec:
      containers:
        - name: mongodb
          image: bitnami/mongodb:7.0.9
          ports:
            - containerPort: 27017
              name: tcp
          volumeMounts:
            - name: {{ .Release.Namespace }}-{{ .Release.Name }}-mongodb-data
              mountPath: /bitnami/mongodb
          securityContext:
            allowPrivilegeEscalation: true
            capabilities: { }
            privileged: false
            readOnlyRootFilesystem: false
            runAsUser: 1001
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: {{ include "status-service.fullname" . }}-mongodb-credentials
                optional: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: 1001
  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Namespace }}-{{ .Release.Name }}-mongodb-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.storage.mongodb.master.requests }}
        storageClassName: {{ .Values.storage.mongodb.master.class }}
        volumeMode: Filesystem
{{- end -}}
